apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-editor
rules:
- apiGroups: ["", "apps", "networking.k8s.io"]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims", "deployments", "statefulsets", "ingresses"]
  verbs: ["get", "watch", "list", "update", "patch", "create", "delete"]
