apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devops-admin
rules:
- apiGroups: ["", "apps", "batch", "autoscaling", "extensions", "policy", "rbac.authorization.k8s.io", "storage.k8s.io", "apiextensions.k8s.io", "admissionregistration.k8s.io", "networking.k8s.io", "scheduling.k8s.io", "coordination.k8s.io", "node.k8s.io", "events.k8s.io"]
  resources: ["*"]
  verbs: ["*"]